version: '3.8'

services:
  # Servicio Redis
  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Interfaz web para Redis (Redis Commander)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-interface
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    networks:
      - redis-network
    depends_on:
      redis:
        condition: service_healthy

  # Alternativa: RedisInsight (interfaz oficial de Redis)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    networks:
      - redis-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local

networks:
  redis-network:
    driver: bridge